version: '3'

services:
  app:
    build: .
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - mariadb
      - adminer
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    volumes:
      - ./:/home/node/app
    command: sh -c "yarn install && yarn start:dev"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
    ports:
        - $DB_PORT:$DB_PORT
    restart: always

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_TYPE: server
      ADMINER_DEFAULT_SERVER: $DB_HOST
      ADMINER_DEFAULT_PORT: $DB_PORT
      ADMINER_DEFAULT_DATABASE: $DB_NAME
      ADMINER_DEFAULT_USERNAME: $DB_USER
      ADMINER_DEFAULT_PASSWORD: $DB_PASS
    ports:
      - 8083:8080
    expose:
      - 8080
    links:
      - mariadb
    depends_on: 
      - mariadb

networks: 
  app:
    driver: bridge

volumes: 
  mariadb: